version: "3.8"

services: 
  wrapper-btc:
    build: 
      context: .
      dockerfile: Dockerfile.btc
    restart: always
    env_file: 
      - .node1.env

  wrapper-trx:
    build: 
      context: .
      dockerfile: Dockerfile.trx
    restart: always
    env_file: 
      - .node1.env