version: "3.7"

services:
  mongo:
    container_name: wrapper-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
    restart: always

  btc:
    container_name: wrapper-btc
    build:
      context: .
      dockerfile: Dockerfile.btc
    depends_on:
      - mongo
    links:
      - mongo
    env_file: .env
    restart: always