version: "3.7"

services:
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   ports: 
  #     - 27017:27017
  #   restart: always

  wrapper:
    container_name: wrapper-node
    build:
      context: .
      dockerfile: Dockerfile.node
    # depends_on:
    #   - mongo
    # links:
    #   - mongo
    env_file: .env
    restart: always