version: "3.7"

services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  wrapper-btc:
    build:
      context: .
      dockerfile: Dockerfile.btc
    links:
      - mongo
    depends_on:
      - mongo
    env_file: .env
    restart: always
  # wrapper-trx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.trx
  #   restart: always

networks:
  app:
    driver: bridge
