version: "3.7"

services:
  wrapper-mongo-1:
    container_name: wrapper-mongo-1
    image: mongo
    command: mongod --port 27021
    volumes:
      - ./data-1:/data/db
    ports: 
      - 27021:27021
    restart: always

  wrapper-btc-1:
    container_name: wrapper-btc-1
    build:
      context: .
      dockerfile: Dockerfile.btc
    depends_on:
      - wrapper-mongo-1
    links:
      - wrapper-mongo-1
    env_file: .node1.env
    restart: always

  wrapper-mongo-2:
    container_name: wrapper-mongo-2
    image: mongo
    command: mongod --port 27022
    volumes:
      - ./data-2:/data/db
    ports: 
      - 27022:27022
    restart: always

  wrapper-btc-2:
    container_name: wrapper-btc-2
    build:
      context: .
      dockerfile: Dockerfile.btc
    depends_on:
      - wrapper-mongo-2
    links:
      - wrapper-mongo-2
    env_file: .node2.env
    restart: always

  wrapper-mongo-3:
    container_name: wrapper-mongo-3
    image: mongo
    command: mongod --port 27023
    volumes:
      - ./data-3:/data/db
    ports: 
      - 27023:27023
    restart: always

  wrapper-btc-3:
    container_name: wrapper-btc-3
    build:
      context: .
      dockerfile: Dockerfile.btc
    depends_on:
      - wrapper-mongo-3
    links:
      - wrapper-mongo-3
    env_file: .node3.env
    restart: always

networks:
    wrapper-network-1:
      driver: bridge
    wrapper-network-2:
      driver: bridge
    wrapper-network-3:
      driver: bridge